[package]
name = "base-db"
version = "0.0.0"
repository.workspace = true
description = "Basic database traits for wgsl-analyzer. The concrete DB is defined by `ide` (aka `wa_ap_ide`)."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
la-arena.workspace = true
dashmap.workspace = true
salsa.workspace = true
query-group.workspace = true
rustc-hash.workspace = true
triomphe.workspace = true
semver.workspace = true
tracing.workspace = true

# local deps
syntax.workspace = true
vfs.workspace = true
span.workspace = true
intern.workspace = true

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"
