[package]
name = "syntax"
version = "0.0.0"
repository.workspace = true
description = "Concrete syntax tree definitions for wgsl-analyzer."

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
either.workspace = true
itertools.workspace = true
rowan.workspace = true
parser.workspace = true
smol_str = "0.3.2"
lexer.workspace = true

[dev-dependencies]
expect-test.workspace = true
test-utils.workspace = true
